### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by tenda96** [GlenLowland/jellyfin-tizen-npm-publish#1] opened 2024-05-10 18:13 UTC
Thanks for making this module for tizenbrew, i'm really glad someone made one for jellyfin <3

However i've managed to install it, but when i try to connect to my jellyfin local server and error shows up with a pop-up that say something like: "can't connect to the selected server right now. Please make sure that the server is in execution and retry."

![PXL_20240510_195204405](https://github.com/GlenLowland/jellyfin-tizen-npm-publish/assets/28265754/9333fc06-e4a3-4408-a8eb-687b9e8d0f67)
 
In the title pop up there is a long message that say:"https://unpkg.com/@glenlowland/jellyfin-tizen@0.1.27/www/index.html#!/addserver.html"

The jellyfin server is working fine and the ip and local port are correct.

Maybe it says that because i've already have the jellyfin app installed on tv from [georift](https://github.com/Georift/install-jellyfin-tizen)? (And that one is working fine)

Do you know what could be? 

Please, let me know.
Thank you! Have a nice day :)

**Comment by GlenLowland** [comment] 2024-05-12 18:59
Hello, thank you for your feedback!
This app shouldn't conflict with locally installed one, at some point I had both on my TV and both worked fine.
It is strange it connects through locally installed app and not through TizenBrew app.
Could you please retry with the new version? I've just updated the build script and released [0.1.28](https://github.com/GlenLowland/jellyfin-tizen-npm-publish/releases/tag/0.1.28) version which is using newly released Jellyfin Web 10.9.0 package. Note that you might want to update your Jellyfin server first.
Let me know if the issue still persists.

**Comment by tenda96** [comment] 2024-05-12 19:33
Thanks for the answer!
Yesterday i've tried many time to install and uninstall the two apps, to see if with or without was working... but no luck.

Now i've just installed your new release, but nothing changed :( 
Only the error is changed haha
Now the title of the popup is: https://unpkg.com/@glenlowland/jellyfin-tizen@0.1.28/www/index.html#!/addserver.html"
But it's the same error, the only thing changed is the version.
The server is running on the latest image of jelly (updated this morning).
Let me know,
Thanks!

**Comment by GlenLowland** [comment] 2024-05-12 19:43
Ah, okay. Well, still can't figure out the reason why, but just as a part of diagnostics, could you please try to open your jellyfin server from built-in browser in the TV itself? Just type in your server and port in url... Cause all the TizenBrew loader does is basically redirects the browser instance to my package url.

**Comment by tenda96** [comment] 2024-05-12 20:12
Yes i've tried to type the address in the web browser and is working fine:
![PXL_20240512_215520254](https://github.com/GlenLowland/jellyfin-tizen-npm-publish/assets/28265754/2afca46a-abdb-43a2-8d62-f716f60703fd)

It's very strange :/

**Comment by GlenLowland** [comment] 2024-05-12 20:39
Okay, I have reproduced!
I am just using reverse proxy that allows me to access and use my server as `myserver.com`.
It also provides LetsEncrypt SSL certificate for HTTPS connection.
But I can reproduce if I specify my Jellyfin IP and port instead.
So this is the root cause:
![root cause](https://github.com/GlenLowland/jellyfin-tizen-npm-publish/assets/127740393/0230ca0c-37ca-45ba-aef9-f6530bfeb412)
Modern browsers do not allow accessing HTTP resource when the page is loaded over HTTPS :(
Since the package is loaded over a secure connection, the jellyfin server must be accessible over HTTPS as well.
One way to do it is to use a reverse proxy, such as `nginx-proxy-manager`.
For my homeserver I've followed this kind of setup: https://www.youtube.com/watch?v=qlcVx-k-02E
I know it requires more setup but that is the only way to go - making your jellyfin server accessible over HTTPS and using a valid SSL certificate (such as LetsEncrypt one that you can get for free).
On the bright side the reverse proxy is going to make your life a lot easier when using local services, docker containers, etc..

**Comment by GlenLowland** [comment] 2024-05-12 20:51
I have also updated the README and added this as a known issue.

**Comment by tenda96** [comment] 2024-05-12 21:12
Ah ok i saw the readmi. 

However thank you for your efforts. Maybe i will do it, but for now if the other app is working i think i will stick to that for now.
Thank you anyway 😎

**Comment by GlenLowland** [comment] 2024-06-29 16:18
@tenda96 there is an update to TizenBrew - if you try to update TizenBrew to v1.3.0 and try to connect to your Jellyfin server. It should work now over HTTP too, fixed on TizenBrew side.

**Comment by tenda96** [comment] 2024-06-29 17:23
Yep is working fine now! Thanks for let me know it! 😁

**Closed as completed** 2024-06-29 17:58 UTC
